APPROX_BDAYS_PER_MONTH = 21
APPROX_BDAYS_PER_YEAR = 252
APPROX_BHOURS_PER_YEAR = APPROX_BDAYS_PER_YEAR * 4
APPROX_BHHRS_PER_YEAR = APPROX_BHOURS_PER_YEAR * 2

MONTHS_PER_YEAR = 12
WEEKS_PER_YEAR = 52
QTRS_PER_YEAR = 4

HALF_HOURLY = '30min'
HOURLY = 'hourly'
DAILY = 'daily'
WEEKLY = 'weekly'
MONTHLY = 'monthly'
QUARTERLY = 'quarterly'
YEARLY = 'yearly'

ANNUALIZATION_FACTORS = {
    HALF_HOURLY: APPROX_BHHRS_PER_YEAR,
    HOURLY: APPROX_BHOURS_PER_YEAR,
    DAILY: APPROX_BDAYS_PER_YEAR,
    WEEKLY: WEEKS_PER_YEAR,
    MONTHLY: MONTHS_PER_YEAR,
    QUARTERLY: QTRS_PER_YEAR,
    YEARLY: 1
}
